<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VendorSeeder extends Seeder
{
    /**
     * Seed core vendor records plus their category relationships so the
     * storefront has real data to work with.
     */
    public function run(): void
    {
        DB::table('vendor_categories')->delete();
        DB::table('vendors')->delete();

        $now = Carbon::now();

        $vendors = [
            [
                'id' => 1,
                'name' => 'Downtown Deli',
                'slug' => 'downtown-deli',
                'desc' => 'Neighbourhood deli specialising in artisan sandwiches and soups.',
                'short_desc' => 'Sandwiches & salads',
                'address' => '123 Sheikh Zayed Rd, Dubai',
                'latitude' => 25.2048,
                'longitude' => 55.2708,
                'order_min_amount' => 35,
                'order_pre_time' => '25',
                'commission_percent' => 5,
                'commission_fixed_per_order' => 2,
                'dine_in' => 1,
                'takeaway' => 1,
                'delivery' => 1,
                'status' => 1,
                'show_slot' => 0,
                'admin_rating' => 4.5,
                'rating' => 4.6,
                'phone_no' => '+9715000001',
                'email' => 'hello@downtowndeli.test',
                'website' => 'https://downtowndeli.test',
                'pincode' => '00001',
                'city' => 'Dubai',
                'state' => 'Dubai',
                'country' => 'AE',
                'logo' => 'default/default_image.png',
                'banner' => 'default/default_image.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Seaview Grocery',
                'slug' => 'seaview-grocery',
                'desc' => 'Convenience grocery focused on imported goods and ready-to-cook kits.',
                'short_desc' => 'Urban grocery mart',
                'address' => '45 Corniche St, Abu Dhabi',
                'latitude' => 24.4667,
                'longitude' => 54.3667,
                'order_min_amount' => 50,
                'order_pre_time' => '35',
                'commission_percent' => 4,
                'commission_fixed_per_order' => 1.5,
                'dine_in' => 0,
                'takeaway' => 1,
                'delivery' => 1,
                'status' => 1,
                'show_slot' => 0,
                'admin_rating' => 4.2,
                'rating' => 4.3,
                'phone_no' => '+9715000002',
                'email' => 'care@seaviewgrocery.test',
                'website' => 'https://seaviewgrocery.test',
                'pincode' => '00002',
                'city' => 'Abu Dhabi',
                'state' => 'Abu Dhabi',
                'country' => 'AE',
                'logo' => 'default/default_image.png',
                'banner' => 'default/default_image.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'Marhaba Pharmacy',
                'slug' => 'marhaba-pharmacy',
                'desc' => '24/7 community pharmacy with wellness programmes and home delivery.',
                'short_desc' => 'Community pharmacy',
                'address' => '78 Airport Rd, Sharjah',
                'latitude' => 25.3463,
                'longitude' => 55.4210,
                'order_min_amount' => 20,
                'order_pre_time' => '15',
                'commission_percent' => 3,
                'commission_fixed_per_order' => 1,
                'dine_in' => 0,
                'takeaway' => 1,
                'delivery' => 1,
                'status' => 1,
                'show_slot' => 0,
                'admin_rating' => 4.8,
                'rating' => 4.7,
                'phone_no' => '+9715000003',
                'email' => 'support@marhabapharmacy.test',
                'website' => 'https://marhabapharmacy.test',
                'pincode' => '00003',
                'city' => 'Sharjah',
                'state' => 'Sharjah',
                'country' => 'AE',
                'logo' => 'default/default_image.png',
                'banner' => 'default/default_image.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Urban Basket',
                'slug' => 'urban-basket',
                'desc' => 'Lifestyle supermarket curating organic produce and speciality goods.',
                'short_desc' => 'Organic supermarket',
                'address' => '12 Marina Promenade, Dubai',
                'latitude' => 25.0800,
                'longitude' => 55.1400,
                'order_min_amount' => 60,
                'order_pre_time' => '40',
                'commission_percent' => 6,
                'commission_fixed_per_order' => 2.5,
                'dine_in' => 0,
                'takeaway' => 1,
                'delivery' => 1,
                'status' => 1,
                'show_slot' => 0,
                'admin_rating' => 4.9,
                'rating' => 4.8,
                'phone_no' => '+9715000004',
                'email' => 'orders@urbanbasket.test',
                'website' => 'https://urbanbasket.test',
                'pincode' => '00004',
                'city' => 'Dubai',
                'state' => 'Dubai',
                'country' => 'AE',
                'logo' => 'default/default_image.png',
                'banner' => 'default/default_image.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'Express Mart',
                'slug' => 'express-mart',
                'desc' => 'Quick commerce store for snacks, beverages, and daily essentials.',
                'short_desc' => 'Quick commerce mart',
                'address' => '5 King Faisal St, Ajman',
                'latitude' => 25.4052,
                'longitude' => 55.5136,
                'order_min_amount' => 25,
                'order_pre_time' => '20',
                'commission_percent' => 4,
                'commission_fixed_per_order' => 1.2,
                'dine_in' => 0,
                'takeaway' => 1,
                'delivery' => 1,
                'status' => 1,
                'show_slot' => 0,
                'admin_rating' => 4.1,
                'rating' => 4.2,
                'phone_no' => '+9715000005',
                'email' => 'hello@expressmart.test',
                'website' => 'https://expressmart.test',
                'pincode' => '00005',
                'city' => 'Ajman',
                'state' => 'Ajman',
                'country' => 'AE',
                'logo' => 'default/default_image.png',
                'banner' => 'default/default_image.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('vendors')->insert($vendors);

        $vendorCategories = [
            ['vendor_id' => 1, 'category_id' => 3, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['vendor_id' => 1, 'category_id' => 7, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['vendor_id' => 2, 'category_id' => 4, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['vendor_id' => 3, 'category_id' => 5, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['vendor_id' => 4, 'category_id' => 4, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['vendor_id' => 4, 'category_id' => 8, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['vendor_id' => 5, 'category_id' => 6, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
        ];

        DB::table('vendor_categories')->insert($vendorCategories);
    }
}

